name: learnware_backend
channels:
  - anaconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - click=8.0.4=py38h06a4308_0
  - flask=2.2.2=py38h06a4308_0
  - flask-cors=3.0.10=pyhd3eb1b0_0
  - importlib-metadata=6.0.0=py38h06a4308_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jinja2=3.1.2=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - markupsafe=2.1.1=py38h7f8727e_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_3
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.1=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - werkzeug=2.2.3=py38h06a4308_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zipp=3.11.0=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_0
prefix: /home/wnjxyk/miniconda3/envs/learnware_backend
