apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-egress
  namespace: learnware
spec:
  podSelector:
    matchLabels:
      app: learnware-check
  policyTypes:
  - Egress